In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r"C:\Users\amitd\OneDrive\Desktop\Python Bootcamp\Loan payments data.csv")

In [3]:
dataset

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
0,xqd20166231,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/14/2016 19:31,NaN,45,High School or Below,male
1,xqd20168902,PAIDOFF,1000,30,9/8/2016,10/7/2016,10/7/2016 9:00,NaN,50,Bechalor,female
2,xqd20160003,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/25/2016 16:58,NaN,33,Bechalor,female
3,xqd20160004,PAIDOFF,1000,15,9/8/2016,9/22/2016,9/22/2016 20:00,NaN,27,college,male
4,xqd20160005,PAIDOFF,1000,30,9/9/2016,10/8/2016,9/23/2016 21:36,NaN,28,college,female
...,...,...,...,...,...,...,...,...,...,...,...
495,xqd20160496,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/14/2016 19:08,3.0,28,High School or Below,male
496,xqd20160497,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,10/10/2016 20:02,14.0,26,High School or Below,male
497,xqd20160498,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,9/29/2016 11:49,3.0,30,college,male
498,xqd20160499,COLLECTION_PAIDOFF,1000,30,9/12/2016,11/10/2016,11/11/2016 22:40,1.0,38,college,female
499,xqd20160500,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/19/2016 11:58,8.0,28,High School or Below,male

In [8]:
dataset.isnull()

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
0,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False

In [6]:
dataset.notnull()

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
0,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,False,True,True,True
2,True,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,True,False,True,True,True
4,True,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
495,True,True,True,True,True,True,True,True,True,True,True
496,True,True,True,True,True,True,True,True,True,True,True
497,True,True,True,True,True,True,True,True,True,True,True
498,True,True,True,True,True,True,True,True,True,True,True
499,True,True,True,True,True,True,True,True,True,True,True

In [7]:
dataset.isnull().sum()

Loan_ID             0
loan_status         0
Principal           0
terms               0
effective_date      0
due_date            0
paid_off_time     100
past_due_days     300
age                 0
education           0
Gender              0
dtype: int64

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Loan_ID         500 non-null    object
 1   loan_status     500 non-null    object
 2   Principal       500 non-null    int64
 3   terms           500 non-null    int64
 4   effective_date  500 non-null    object
 5   due_date        500 non-null    object
 6   paid_off_time   400 non-null    object
 7   past_due_days   200 non-null    float64
 8   age             500 non-null    int64
 9   education       500 non-null    object
 10  Gender          500 non-null    object
dtypes: float64(1), int64(3), object(7)
memory usage: 43.1+ KB

In [10]:
dataset.select_dtypes(include="float64").columns

Index(['past_due_days'], dtype='object')

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
si = SimpleImputer(strategy="mean")

In [13]:
si.fit_transform(dataset[["past_due_days"]])

array([[36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [36.01],
       [76.  ],
       [61.  ],
       [61.  ],
       [76.  ],
       [76.  ],
       [75.  ],
       [60.  ],
       [60.  ],
       [60.  ],
       [75.  ],
       [60.  ],
       [75.  ],
       [60.  ],
       [60.  ],
       [60.  ],
       [60.  ],
       [60.  ],
       [75.  ],
       [60.  ],
       [75.  ],
       [60.  ],
       [60.  ],
       [60.  ],
       [75.  ],
       [75.  ],
       [59.  ],
       [74.  ],
       [29.  ],
       [59.  ],
       [59.  ],
       [44.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [74.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [29.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [59.  ],
       [74.  ],
       [74.  ],
       [59.  ],
       [59.  ],
       [29.  ],
       [74.  ],
       [59.  ],
       [74.  ],
       [44.  ],
       [74.  ],
       [74.  ],
       [59.  ],
       [29.  ],
       [74.  ],
       [59.  ],
       [58.  ],
       [73.  ],
       [28.  ],
       [58.  ],
       [ 2.  ],
       [ 4.  ],
       [13.  ],
       [ 5.  ],
       [ 3.  ],
       [12.  ],
       [ 2.  ],
       [27.  ],
       [44.  ],
       [ 5.  ],
       [ 1.  ],
       [27.  ],
       [ 2.  ],
       [ 1.  ],
       [ 2.  ],
       [ 2.  ],
       [ 1.  ],
       [ 3.  ],
       [12.  ],
       [25.  ],
       [ 3.  ],
       [ 2.  ],
       [ 4.  ],
       [ 2.  ],
       [ 1.  ],
       [24.  ],
       [ 1.  ],
       [ 2.  ],
       [ 2.  ],
       [ 1.  ],
       [ 3.  ],
       [ 4.  ],
       [ 2.  ],
       [ 2.  ],
       [ 1.  ],
       [ 1.  ],
       [36.  ],
       [ 1.  ],
       [ 7.  ],
       [ 5.  ],
       [14.  ],
       [ 2.  ],
       [ 1.  ],
       [28.  ],
       [ 2.  ],
       [ 2.  ],
       [25.  ],
       [23.  ],
       [ 3.  ],
       [ 1.  ],
       [ 3.  ],
       [ 4.  ],
       [ 3.  ],
       [ 3.  ],
       [ 6.  ],
       [ 2.  ],
       [38.  ],
       [19.  ],
       [ 2.  ],
       [ 2.  ],
       [ 2.  ],
       [ 7.  ],
       [ 5.  ],
       [ 4.  ],
       [ 1.  ],
       [ 1.  ],
       [ 4.  ],
       [ 1.  ],
       [ 4.  ],
       [52.  ],
       [ 2.  ],
       [24.  ],
       [51.  ],
       [ 3.  ],
       [ 2.  ],
       [29.  ],
       [ 5.  ],
       [ 9.  ],
       [27.  ],
       [ 1.  ],
       [29.  ],
       [ 3.  ],
       [ 1.  ],
       [ 7.  ],
       [ 4.  ],
       [ 3.  ],
       [56.  ],
       [ 2.  ],
       [13.  ],
       [ 1.  ],
       [ 6.  ],
       [29.  ],
       [14.  ],
       [ 3.  ],
       [ 2.  ],
       [ 3.  ],
       [14.  ],
       [ 3.  ],
       [ 1.  ],
       [ 8.  ]])

In [14]:
ar = si.fit_transform(dataset[["past_due_days"]])

In [16]:
pd.DataFrame(ar, columns = dataset.select_dtypes(include="float64").columns)

     past_due_days
0            36.01
1            36.01
2            36.01
3            36.01
4            36.01
..             ...
495           3.00
496          14.00
497           3.00
498           1.00
499           8.00

[500 rows x 1 columns]

In [17]:
new_dataset = pd.DataFrame(ar, columns=dataset.select_dtypes(include="float64").columns)

In [18]:
new_dataset.isnull().sum()

past_due_days    0
dtype: int64

In [19]:
dataset["past_due_days"].mean()

np.float64(36.01)