In [1]:
import pandas as pd
dataset = pd.read_csv(r"C:\Users\amitd\OneDrive\Desktop\Python Bootcamp\test_Y3wMUE5_7gLdaTN.csv")

In [2]:
dataset.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban

In [3]:
dataset.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [4]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0], inplace=True)

In [5]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [6]:
en_data = dataset[["Gender", "Married"]]

In [7]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  367 non-null    bool
 1   Gender_Male    367 non-null    bool
 2   Married_No     367 non-null    bool
 3   Married_Yes    367 non-null    bool
dtypes: bool(4)
memory usage: 1.6 KB

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe = OneHotEncoder()

In [10]:
ohe.fit_transform(en_data).toarray()

array([[0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.]], shape=(367, 4))

In [11]:
ar = ohe.fit_transform(en_data).toarray()

In [12]:
pd.DataFrame(ar, columns=["Gender_Female", "Gender_Male", "Married_No", "Married_Ye"])

     Gender_Female  Gender_Male  Married_No  Married_Ye
0              0.0          1.0         0.0         1.0
1              0.0          1.0         0.0         1.0
2              0.0          1.0         0.0         1.0
3              0.0          1.0         0.0         1.0
4              0.0          1.0         1.0         0.0
..             ...          ...         ...         ...
362            0.0          1.0         0.0         1.0
363            0.0          1.0         0.0         1.0
364            0.0          1.0         1.0         0.0
365            0.0          1.0         0.0         1.0
366            0.0          1.0         1.0         0.0

[367 rows x 4 columns]

In [13]:
df = pd.DataFrame({"Name" : ["Appwars", "Python", "SQL", "ML", "PowerBI", "NLP", "LLM"]})

In [14]:
df

      Name
0  Appwars
1   Python
2      SQL
3       ML
4  PowerBI
5      NLP
6      LLM

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
le.fit_transform(df["Name"])

array([0, 5, 6, 2, 4, 3, 1])

In [18]:
df["en_name"] = le.fit_transform(df["Name"])

In [19]:
df

      Name  en_name
0  Appwars        0
1   Python        5
2      SQL        6
3       ML        2
4  PowerBI        4
5      NLP        3
6      LLM        1